global:
  scrape_interval: 5s      # scrape every 5 seconds
  evaluation_interval: 5s

scrape_configs:
  - job_name: "anomaly_detector"
    static_configs:
      # host.docker.internal resolves to your Windows host from inside Docker
      - targets: ["host.docker.internal:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "anomaly_detector"
    metrics_path: /metrics
