global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "anomaly_detector"
    static_configs:
      - targets: ["host.docker.internal:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "anomaly_detector"
    metrics_path: /metrics
    scrape_timeout: 4s
